name: "\U0001F41E Bug Report"
description: Create a report to help us improve functionality
title: ''
labels: '🐞[BUG]: '
assignees: ''
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Please describe the issue you encountered in detail.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the bug you encountered.
      placeholder: What happened? What did you expect to happen?

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please describe the steps to reproduce the issue.
      placeholder: How can we reproduce the issue?

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is the bug?
      options:
        - Critical
        - Major
        - Minor
      default: Major

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: What is the priority of this bug report?
      options:
        - High
        - Medium
        - Low
      default: Medium
