name: Feature Request
description: Suggest a new feature for this project
title: '🚀[FET]: '
labels: 'feature request'
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Please describe your feature request in detail. 

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the feature you are requesting. 
      placeholder: What feature would you like to see implemented?

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature important to you? How will it improve the project or benefit its users?
      placeholder: Why do you think this feature should be added?

  - type: textarea
    id: proposed-implementation
    attributes:
      label: Proposed Implementation
      description: How do you envision this feature being implemented? Are there any technical details or requirements to consider?
      placeholder: How do you propose implementing this feature?

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: What is the priority of this feature request?
      options:
        - High
        - Medium
        - Low

  - type: markdown
    id: feature-request
    attributes:
      value: |
        ## Feature Request
        Please describe your feature request in detail.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Feature
        - Enhancement
        - Integration request
        - Accessibility request
        - Performance Improvement

  - type: textarea
    id: proposed-implementation
    attributes:
      label: Proposed Implementation
      description: How do you envision this feature being implemented? Are there any technical details or requirements to consider?
      placeholder: How do you propose implementing this feature?

  - type: markdown
    attributes:
#     id: issue-types
      value: "## Types of Issues"
            
