name: "\U0001F9EF Report Security Vulnerability"
description: Create a report to help us improve security
title: '🧯[SEC] '
labels: ['security', 'bug']

body:
- type: markdown
  attributes:
    value: |
      ## Security Vulnerability Report
      
      Please describe the security vulnerability you have found in detail. Include information such as:
      
      * A clear description of the vulnerability
      * Steps to reproduce the vulnerability
      * The potential impact of the vulnerability
      * Any mitigating factors or workarounds

- type: input
  id: impact
  attributes:
    label: 'Potential Impact'
    description: 'What could happen if this vulnerability is not addressed?'
    placeholder: 'Enter potential impact here'

- type: input
  id: steps-to-reproduce
  attributes:
    label: 'Steps to Reproduce'
    description: 'Provide a clear set of steps to reproduce the vulnerability'
    placeholder: 'Enter steps to reproduce here'

- type: input
  id: mitigating-factors
  attributes:
    label: 'Mitigating Factors'
    description: 'Are there any mitigating factors or workarounds to reduce the risk?'
    placeholder: 'Enter mitigating factors here'

- type: input
  id: attachments
  attributes:
    label: 'Attachments'
    description: 'Attach any screenshots, logs, or other relevant materials'
    placeholder: 'attach file here'

- type: markdown
  id: additional-info
  attributes:
    value: |
      ## Additional Information
      
      Please include any additional information that may be helpful in understanding or addressing the security vulnerability.
