name: "\U0001F3C3 User Journey"
description: Describe a user journey for a specific task
title: '🏃[REQ]: <as this role, I want to be able to x> '
labels: 'user journey, enhancement'
body:
  - type: markdown
    attributes:
      value: |
        ## User Journey
        Please describe a user journey for a specific task.

  - type: textarea
    id: persona
    attributes:
      label: Persona
      description: Who is the user for this journey? What are their goals, needs, and pain points?
      placeholder: Describe the persona for this user journey.

  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What is the user trying to achieve in this journey? What is the desired outcome?
      placeholder: Describe the goal for this user journey.

  - type: textarea
    id: steps
    attributes:
      label: Steps
      description: What are the specific steps the user takes to achieve their goal in this journey?
      placeholder: Describe the steps for this user journey.

  - type: textarea
    id: pain-points
    attributes:
      label: Pain Points
      description: What pain points or challenges does the user encounter in this journey? What are the opportunities for improvement?
      placeholder: Describe the pain points for this user journey.
